terraform {
  required_version = ">= 1.0.0"
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
    okta = { source = "okta/okta", version = "~> 4.0" }
  }
  # Backend is generated by your setup.sh script
  backend "s3" {}
}

provider "aws" {
  region = var.region
}

# We will uncomment this when we add the Identity module in Phase 3
# provider "okta" {
#   org_name  = var.okta_org_name
#   base_url  = "okta.com"
#   api_token = var.okta_api_token
# }